/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ServiceProvider, ServiceType, PakistaniCity } from './/types';

export const PAKISTANI_AREAS: Record<PakistaniCity, string[]> = {
  Karachi: ['Clifton', 'DHA', 'Gulshan-e-Iqbal', 'Johar', 'North Nazimabad', 'KDA'],
  Lahore: ['Gulberg', 'Model Town', 'DHA Phase 5', 'Johar Town', 'Samanabad', 'Wapda Town'],
  Islamabad: ['Sector F-6', 'Sector F-10', 'Sector G-11', 'Sector H-9', 'Bahria Town', 'DHA Phase 2'],
};

export const SERVICES_CATALOG: Array<{
  type: ServiceType;
  icon: string;
  description: string;
  avgCostRange: string;
  avgResponse: string;
  features: string[];
}> = [
  {
    type: 'AC Repair',
    icon: 'Snowflake',
    description: 'Intelligent cooling solutions including standard inspection, filter deep-cleans, gas charging, and emergency capacitor replacements.',
    avgCostRange: 'Rs. 1,500 - 3,000',
    avgResponse: '30-60 min',
    features: ['Inverter Specialist', 'Pressure Leak Detection', '90-Day Service Warranty'],
  },
  {
    type: 'Plumbing',
    icon: 'Wrench',
    description: 'Rapid-response hydraulic repairs, leakage resolutions, high-pressure line drainage, and multi-story tank sanitation checks.',
    avgCostRange: 'Rs. 1,000 - 2,500',
    avgResponse: '30-90 min',
    features: ['Ultrasonic Leak Sensing', 'PPR/G.I. Pipeline Certified', 'Emergency Drain Clearing'],
  },
  {
    type: 'Electrician',
    icon: 'Zap',
    description: 'Expert residential smart wiring, DB board load balancing, circuit breaker overhauls, UPS configuration, and safe stabilizer troubleshooting.',
    avgCostRange: 'Rs. 800 - 2,000',
    avgResponse: '30-60 min',
    features: ['Thermal Overload Audits', 'Solar-Inverter Integration', 'Short-Circuit Diagnosis'],
  },
  {
    type: 'Home Cleaning',
    icon: 'Sparkles',
    description: 'Eco-conscious full-home sanitation sweeps, steam-heated upholstery treatments, post-renovation intensive cleans, and deep kitchen sanitization.',
    avgCostRange: 'Rs. 2,000 - 5,000',
    avgResponse: '60-120 min',
    features: ['Non-Toxic High-Grade Agents', 'Deep Carpet Extraction', 'HEPA Filter Extraction'],
  },
  {
    type: 'Carpenter',
    icon: 'Hammer',
    description: 'Authentic wooden furniture repairs, premium hydraulic cabinet setup, complex interlocking door locks installation, and micro-polishing services.',
    avgCostRange: 'Rs. 1,500 - 4,000',
    avgResponse: '60-120 min',
    features: ['Teak/Sheesham Restorations', 'Concealed Hinge Fitting', 'Multi-Point Deadbolt Setup'],
  },
  {
    type: 'Painter',
    icon: 'Paintbrush',
    description: 'Premium emulsion wall coatings, decorative modern textures, dampness prevention layouts, and exterior weatherproof protective paintings.',
    avgCostRange: 'Rs. 3,000 - 8,000',
    avgResponse: '120-240 min',
    features: ['Moisture Meter Pre-Scans', 'Zero-VOC Odorless Formulation', 'Wall Putty Surface Refining'],
  },
];

export const SERVICE_PROVIDERS_DATABASE: ServiceProvider[] = [
  // AC Repair
  {
    provider_id: 'PRV-AC-01',
    name: 'Karachi Cool-Tech Solutions',
    service_type: 'AC Repair',
    rating: 4.8,
    city: 'Karachi',
    areas: ['Clifton', 'DHA', 'Gulshan-e-Iqbal'],
    experience_years: 8,
    response_time_min: 35,
    emergency_available: true,
    hourly_rate_pkr: 2200,
    active_bookings_count: 2,
  },
  {
    provider_id: 'PRV-AC-02',
    name: 'Lahore Smart Climate Specialists',
    service_type: 'AC Repair',
    rating: 4.9,
    city: 'Lahore',
    areas: ['Gulberg', 'Model Town', 'DHA Phase 5'],
    experience_years: 12,
    response_time_min: 30,
    emergency_available: true,
    hourly_rate_pkr: 2500,
    active_bookings_count: 1,
  },
  {
    provider_id: 'PRV-AC-03',
    name: 'Margalla Thermal Masters',
    service_type: 'AC Repair',
    rating: 4.7,
    city: 'Islamabad',
    areas: ['Sector F-6', 'Sector F-10', 'Sector G-11'],
    experience_years: 6,
    response_time_min: 45,
    emergency_available: false,
    hourly_rate_pkr: 1800,
    active_bookings_count: 0,
  },

  // Plumbing
  {
    provider_id: 'PRV-PL-01',
    name: 'Al-Madina Hydro Services',
    service_type: 'Plumbing',
    rating: 4.6,
    city: 'Karachi',
    areas: ['Gulshan-e-Iqbal', 'Johar', 'North Nazimabad'],
    experience_years: 10,
    response_time_min: 40,
    emergency_available: true,
    hourly_rate_pkr: 1200,
    active_bookings_count: 3,
  },
  {
    provider_id: 'PRV-PL-02',
    name: 'Data Darbar High-Pressure Plumbers',
    service_type: 'Plumbing',
    rating: 4.5,
    city: 'Lahore',
    areas: ['Johar Town', 'Samanabad', 'Wapda Town'],
    experience_years: 9,
    response_time_min: 50,
    emergency_available: true,
    hourly_rate_pkr: 1100,
    active_bookings_count: 2,
  },
  {
    provider_id: 'PRV-PL-03',
    name: 'Capital Flow Mechanics',
    service_type: 'Plumbing',
    rating: 4.9,
    city: 'Islamabad',
    areas: ['Sector F-10', 'Sector G-11', 'Bahria Town'],
    experience_years: 15,
    response_time_min: 25,
    emergency_available: true,
    hourly_rate_pkr: 1800,
    active_bookings_count: 1,
  },
  {
    provider_id: 'PRV-PL-04',
    name: 'Clifton Rapid Hydraulics',
    service_type: 'Plumbing',
    rating: 4.7,
    city: 'Karachi',
    areas: ['Clifton', 'DHA', 'KDA'],
    experience_years: 7,
    response_time_min: 35,
    emergency_available: true,
    hourly_rate_pkr: 1500,
    active_bookings_count: 0,
  },

  // Electrician
  {
    provider_id: 'PRV-EL-01',
    name: 'Karachi Voltage Commanders',
    service_type: 'Electrician',
    rating: 4.9,
    city: 'Karachi',
    areas: ['Clifton', 'DHA', 'Gulshan-e-Iqbal', 'Johar'],
    experience_years: 11,
    response_time_min: 28,
    emergency_available: true,
    hourly_rate_pkr: 1500,
    active_bookings_count: 1,
  },
  {
    provider_id: 'PRV-EL-02',
    name: 'Lahore Power Grid Engineers',
    service_type: 'Electrician',
    rating: 4.8,
    city: 'Lahore',
    areas: ['Gulberg', 'Model Town', 'DHA Phase 5', 'Johar Town'],
    experience_years: 10,
    response_time_min: 35,
    emergency_available: true,
    hourly_rate_pkr: 1400,
    active_bookings_count: 2,
  },
  {
    provider_id: 'PRV-EL-03',
    name: 'Islamabad Smart Volt Integrations',
    service_type: 'Electrician',
    rating: 4.7,
    city: 'Islamabad',
    areas: ['Sector F-6', 'Sector F-10', 'Sector G-11', 'Sector H-9'],
    experience_years: 5,
    response_time_min: 40,
    emergency_available: false,
    hourly_rate_pkr: 1200,
    active_bookings_count: 0,
  },

  // Home Cleaning
  {
    provider_id: 'PRV-CL-01',
    name: 'Pak-Shine Sanitization Hub',
    service_type: 'Home Cleaning',
    rating: 4.9,
    city: 'Karachi',
    areas: ['Clifton', 'DHA', 'Gulshan-e-Iqbal', 'KDA'],
    experience_years: 9,
    response_time_min: 60,
    emergency_available: false,
    hourly_rate_pkr: 2500,
    active_bookings_count: 4,
  },
  {
    provider_id: 'PRV-CL-02',
    name: 'Central Lahore Clean Co.',
    service_type: 'Home Cleaning',
    rating: 4.6,
    city: 'Lahore',
    areas: ['Gulberg', 'Model Town', 'Wapda Town'],
    experience_years: 4,
    response_time_min: 80,
    emergency_available: false,
    hourly_rate_pkr: 2000,
    active_bookings_count: 2,
  },
  {
    provider_id: 'PRV-CL-03',
    name: 'Margalla Spruce Cleaners',
    service_type: 'Home Cleaning',
    rating: 4.8,
    city: 'Islamabad',
    areas: ['Sector F-6', 'Sector F-10', 'Bahria Town', 'DHA Phase 2'],
    experience_years: 7,
    response_time_min: 70,
    emergency_available: true,
    hourly_rate_pkr: 2400,
    active_bookings_count: 1,
  },

  // Carpenter
  {
    provider_id: 'PRV-CP-01',
    name: 'Jinnah Woods & Joinery',
    service_type: 'Carpenter',
    rating: 4.5,
    city: 'Karachi',
    areas: ['Gulshan-e-Iqbal', 'North Nazimabad', 'Johar'],
    experience_years: 14,
    response_time_min: 90,
    emergency_available: false,
    hourly_rate_pkr: 1500,
    active_bookings_count: 1,
  },
  {
    provider_id: 'PRV-CP-02',
    name: 'Royal Mughal Woodcrafts',
    service_type: 'Carpenter',
    rating: 4.9,
    city: 'Lahore',
    areas: ['Gulberg', 'DHA Phase 5', 'Model Town'],
    experience_years: 20,
    response_time_min: 60,
    emergency_available: true,
    hourly_rate_pkr: 2800,
    active_bookings_count: 0,
  },
  {
    provider_id: 'PRV-CP-03',
    name: 'Khyber Joinery & Hinge Specialists',
    service_type: 'Carpenter',
    rating: 4.7,
    city: 'Islamabad',
    areas: ['Sector G-11', 'Sector H-9', 'Bahria Town'],
    experience_years: 8,
    response_time_min: 100,
    emergency_available: false,
    hourly_rate_pkr: 1800,
    active_bookings_count: 3,
  },

  // Painter
  {
    provider_id: 'PRV-PT-01',
    name: 'Karachi Color Spectrum Decorators',
    service_type: 'Painter',
    rating: 4.4,
    city: 'Karachi',
    areas: ['Clifton', 'DHA', 'Johar'],
    experience_years: 12,
    response_time_min: 180,
    emergency_available: false,
    hourly_rate_pkr: 3500,
    active_bookings_count: 1,
  },
  {
    provider_id: 'PRV-PT-02',
    name: 'Lahore Pristine Coating Specialists',
    service_type: 'Painter',
    rating: 4.8,
    city: 'Lahore',
    areas: ['Gulberg', 'Johar Town', 'Samanabad'],
    experience_years: 16,
    response_time_min: 140,
    emergency_available: false,
    hourly_rate_pkr: 4000,
    active_bookings_count: 2,
  },
  {
    provider_id: 'PRV-PT-03',
    name: 'Abis Paint & Anti-Damp Masters',
    service_type: 'Painter',
    rating: 4.9,
    city: 'Islamabad',
    areas: ['Sector F-6', 'Sector F-10', 'DHA Phase 2'],
    experience_years: 11,
    response_time_min: 120,
    emergency_available: true,
    hourly_rate_pkr: 4500,
    active_bookings_count: 0,
  },
];
